# Generated by Django 5.0.6 on 2024-06-27 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Barabanın növü')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yeniləmə tarixi')),
            ],
            options={
                'verbose_name': 'Reel Type',
                'verbose_name_plural': 'Reel Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransportList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nəqliyətin adı')),
                ('length', models.IntegerField(verbose_name='Uzunluq, mm')),
                ('width', models.IntegerField(verbose_name='En, mm')),
                ('height', models.IntegerField(verbose_name='Hündürlük, mm')),
                ('max_load', models.IntegerField(verbose_name='maksimal yükləmə, kq')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yeniləmə tarixi')),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transports',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReelsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Barabanın adı')),
                ('height', models.IntegerField(verbose_name='Barabanın hündürlükü abşıvkalı, mm')),
                ('width', models.IntegerField(verbose_name='Barabanın eni, mm')),
                ('diameter', models.IntegerField(verbose_name='Barabanın diametri, mm')),
                ('diameter_neck', models.IntegerField(verbose_name='Barabanın boğazının diametiri, mm')),
                ('length_neck', models.IntegerField(verbose_name='Barabanın bogazının uzunluğu, mm')),
                ('max_load', models.IntegerField(verbose_name='Maksimal yükləmə, kq')),
                ('mass', models.IntegerField(verbose_name='Barabanın çəkisi, kq')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yeniləmə tarixi')),
                ('reel_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.reeltype', verbose_name='Barabanın növü')),
            ],
            options={
                'verbose_name': 'Reel',
                'verbose_name_plural': 'Reels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CableCal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Sifarişin nömrəsi')),
                ('cod', models.TextField(verbose_name='Kabelin kodu')),
                ('name', models.TextField(db_index=True, verbose_name='Kabelin adı')),
                ('mass', models.TextField(verbose_name='Kabelin çəkisi, kq/m')),
                ('diameter', models.TextField(verbose_name='Kabelin xarici diametri, mm')),
                ('con_num', models.TextField(verbose_name='Kabelin cəriyan keçirən damarların sayı')),
                ('order_len', models.TextField(verbose_name='sifarişin uzunluğu, m')),
                ('max_len', models.TextField(verbose_name='maksimal istehsalat uzunluğu, m')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yeniləmə tarixi')),
                ('transport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.transportlist')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
