# Generated by Django 5.0.6 on 2024-06-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cablecal',
            name='bending_radius',
            field=models.TextField(blank=True, verbose_name='Əyilmə radiusu'),
        ),
        migrations.AddField(
            model_name='cablecal',
            name='brutto_1',
            field=models.TextField(blank=True, verbose_name='Brutto 1 baraban'),
        ),
        migrations.AddField(
            model_name='cablecal',
            name='brutto_all',
            field=models.TextField(blank=True, verbose_name='Brutto ümumi'),
        ),
        migrations.AddField(
            model_name='cablecal',
            name='netto_1',
            field=models.TextField(blank=True, verbose_name='Netto 1 baraban'),
        ),
        migrations.AddField(
            model_name='cablecal',
            name='netto_all',
            field=models.TextField(blank=True, verbose_name='Netto ümumi'),
        ),
        migrations.AddField(
            model_name='cablecal',
            name='reel_len',
            field=models.TextField(blank=True, verbose_name='Bir barabana dolanan miqdar, m'),
        ),
        migrations.AddField(
            model_name='cablecal',
            name='reel_num',
            field=models.TextField(blank=True, verbose_name='Baraban sayı'),
        ),
        migrations.AddField(
            model_name='cablecal',
            name='reel_type',
            field=models.TextField(blank=True, verbose_name='Baraban növü'),
        ),
    ]
