# Generated by Django 5.0.6 on 2024-07-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cablecal_bending_radius_cablecal_brutto_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cablecal',
            name='reel_name',
            field=models.TextField(blank=True, verbose_name='Baraban adı'),
        ),
    ]
