# Generated by Django 6.1 on 2026-08-23 20:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cablecal_reel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CableLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('cod', models.CharField(blank=True, max_length=100, verbose_name='Cable code')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Cable name')),
                ('con_num', models.PositiveIntegerField(default=1, verbose_name='Conductor count')),
                ('order_len', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Order length (m)')),
                ('max_len', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Max production length (m)')),
                ('mass', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=8, verbose_name='Cable mass (kg/m)')),
                ('diameter', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Cable outer diameter (mm)')),
                ('reel_len', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Length per reel (m)')),
                ('reel_num', models.PositiveIntegerField(default=0, verbose_name='Reel count')),
                ('netto_1', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Netto 1 reel (kg)')),
                ('brutto_1', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Brutto 1 reel (kg)')),
                ('netto_all', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Netto total (kg)')),
                ('brutto_all', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Brutto total (kg)')),
                ('bending_radius', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Bending radius (mm)')),
                ('warning', models.TextField(blank=True, default='', verbose_name='Warning')),
            ],
            options={
                'verbose_name': 'Cable line item',
                'verbose_name_plural': 'Cable line items',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='CalculationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winding_margin_mm', models.FloatField(default=50.0, help_text='Unwound margin per flange side.', verbose_name='Winding margin (mm)')),
                ('packing_factor', models.FloatField(default=0.93, verbose_name='Packing factor')),
                ('bending_radius_multiplier', models.FloatField(default=10.0, verbose_name='Bending radius multiplier (x cable diameter)')),
                ('use_flange_height', models.BooleanField(default=False, verbose_name='Use flange height to bound winding')),
            ],
            options={
                'verbose_name': 'Calculation settings',
                'verbose_name_plural': 'Calculation settings',
            },
        ),
        migrations.AddField(
            model_name='cablecal',
            name='margin_override',
            field=models.FloatField(blank=True, null=True, verbose_name='Winding margin override (mm)'),
        ),
        migrations.AddField(
            model_name='cablecal',
            name='packing_override',
            field=models.FloatField(blank=True, null=True, verbose_name='Packing factor override'),
        ),
        migrations.AddConstraint(
            model_name='reelslist',
            constraint=models.CheckConstraint(condition=models.Q(('diameter__gt', models.F('diameter_neck'))), name='reel_diameter_gt_neck'),
        ),
        migrations.AddConstraint(
            model_name='reelslist',
            constraint=models.CheckConstraint(condition=models.Q(('max_load__gt', 0)), name='reel_max_load_pos'),
        ),
        migrations.AddConstraint(
            model_name='reelslist',
            constraint=models.CheckConstraint(condition=models.Q(('length_neck__gt', 0)), name='reel_length_neck_pos'),
        ),
        migrations.AddField(
            model_name='cablelineitem',
            name='cable_cal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='app.cablecal', verbose_name='Calculation'),
        ),
        migrations.AddField(
            model_name='cablelineitem',
            name='reel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.reelslist', verbose_name='Chosen reel'),
        ),
    ]
