# Generated by Django 6.1 on 2026-08-23 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_split_cablecal_to_lineitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reeltype',
            options={'ordering': ['name'], 'verbose_name': 'Reel type', 'verbose_name_plural': 'Reel types'},
        ),
        migrations.AlterField(
            model_name='cablecal',
            name='bending_radius',
            field=models.TextField(blank=True, verbose_name='Bending radius'),
        ),
        migrations.AlterField(
            model_name='cablecal',
            name='brutto_1',
            field=models.TextField(blank=True, verbose_name='Brutto 1 reel'),
        ),
        migrations.AlterField(
            model_name='cablecal',
            name='brutto_all',
            field=models.TextField(blank=True, verbose_name='Brutto total'),
        ),
        migrations.AlterField(
            model_name='cablecal',
            name='cod',
            field=models.TextField(blank=True, verbose_name='Cable code'),
        ),
        migrations.AlterField(
            model_name='cablecal',
            name='con_num',
            field=models.TextField(blank=True, verbose_name='Conductor count'),
        ),
        migrations.AlterField(
            model_name='cablecal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='cablecal',
            name='diameter',
            field=models.TextField(blank=True, verbose_name='Cable outer diameter (mm)'),
        ),
        migrations.AlterField(
            model_name='cablecal',
            name='mass',
            field=models.TextField(blank=True, verbose_name='Cable mass (kg/m)'),
        ),
        migrations.AlterField(
            model_name='cablecal',
            name='max_len',
            field=models.TextField(blank=True, verbose_name='Max production length (m)'),
        ),
        migrations.AlterField(
            model_name='cablecal',
            name='name',
            field=models.TextField(blank=True, db_index=True, verbose_name='Cable name'),
        ),
        migrations.AlterField(
            model_name='cablecal',
            name='netto_1',
            field=models.TextField(blank=True, verbose_name='Netto 1 reel'),
        ),
        migrations.AlterField(
            model_name='cablecal',
            name='netto_all',
            field=models.TextField(blank=True, verbose_name='Netto total'),
        ),
        migrations.AlterField(
            model_name='cablecal',
            name='order_len',
            field=models.TextField(blank=True, verbose_name='Order length (m)'),
        ),
        migrations.AlterField(
            model_name='cablecal',
            name='order_num',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Order number'),
        ),
        migrations.AlterField(
            model_name='cablecal',
            name='reel_len',
            field=models.TextField(blank=True, verbose_name='Length per reel (m)'),
        ),
        migrations.AlterField(
            model_name='cablecal',
            name='reel_name',
            field=models.TextField(blank=True, verbose_name='Reel name'),
        ),
        migrations.AlterField(
            model_name='cablecal',
            name='reel_num',
            field=models.TextField(blank=True, verbose_name='Reel count'),
        ),
        migrations.AlterField(
            model_name='cablecal',
            name='reel_type',
            field=models.TextField(blank=True, verbose_name='Reel type'),
        ),
        migrations.AlterField(
            model_name='cablecal',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.transportlist', verbose_name='Transport'),
        ),
        migrations.AlterField(
            model_name='cablecal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='reelslist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='reelslist',
            name='diameter',
            field=models.IntegerField(verbose_name='Diameter (mm)'),
        ),
        migrations.AlterField(
            model_name='reelslist',
            name='diameter_neck',
            field=models.IntegerField(verbose_name='Core diameter (mm)'),
        ),
        migrations.AlterField(
            model_name='reelslist',
            name='height',
            field=models.IntegerField(verbose_name='Flange height (mm)'),
        ),
        migrations.AlterField(
            model_name='reelslist',
            name='length_neck',
            field=models.IntegerField(verbose_name='Barrel width (mm)'),
        ),
        migrations.AlterField(
            model_name='reelslist',
            name='mass',
            field=models.IntegerField(verbose_name='Reel mass (kg)'),
        ),
        migrations.AlterField(
            model_name='reelslist',
            name='max_load',
            field=models.IntegerField(verbose_name='Max load (kg)'),
        ),
        migrations.AlterField(
            model_name='reelslist',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Reel name'),
        ),
        migrations.AlterField(
            model_name='reelslist',
            name='reel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.reeltype', verbose_name='Reel type'),
        ),
        migrations.AlterField(
            model_name='reelslist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='reelslist',
            name='width',
            field=models.IntegerField(verbose_name='Width (mm)'),
        ),
        migrations.AlterField(
            model_name='reeltype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='reeltype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Reel type name'),
        ),
        migrations.AlterField(
            model_name='reeltype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='transportlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='transportlist',
            name='height',
            field=models.IntegerField(verbose_name='Height (mm)'),
        ),
        migrations.AlterField(
            model_name='transportlist',
            name='length',
            field=models.IntegerField(verbose_name='Length (mm)'),
        ),
        migrations.AlterField(
            model_name='transportlist',
            name='max_load',
            field=models.IntegerField(verbose_name='Max load (kg)'),
        ),
        migrations.AlterField(
            model_name='transportlist',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Transport name'),
        ),
        migrations.AlterField(
            model_name='transportlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='transportlist',
            name='width',
            field=models.IntegerField(verbose_name='Width (mm)'),
        ),
    ]
