# Generated by Django 6.1 on 2026-08-24 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_reeltype_options_alter_cablecal_bending_radius_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cablecal',
            name='bending_radius',
        ),
        migrations.RemoveField(
            model_name='cablecal',
            name='brutto_1',
        ),
        migrations.RemoveField(
            model_name='cablecal',
            name='brutto_all',
        ),
        migrations.RemoveField(
            model_name='cablecal',
            name='cod',
        ),
        migrations.RemoveField(
            model_name='cablecal',
            name='con_num',
        ),
        migrations.RemoveField(
            model_name='cablecal',
            name='diameter',
        ),
        migrations.RemoveField(
            model_name='cablecal',
            name='mass',
        ),
        migrations.RemoveField(
            model_name='cablecal',
            name='max_len',
        ),
        migrations.RemoveField(
            model_name='cablecal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cablecal',
            name='netto_1',
        ),
        migrations.RemoveField(
            model_name='cablecal',
            name='netto_all',
        ),
        migrations.RemoveField(
            model_name='cablecal',
            name='order_len',
        ),
        migrations.RemoveField(
            model_name='cablecal',
            name='reel_len',
        ),
        migrations.RemoveField(
            model_name='cablecal',
            name='reel_name',
        ),
        migrations.RemoveField(
            model_name='cablecal',
            name='reel_num',
        ),
        migrations.RemoveField(
            model_name='cablecal',
            name='reel_type',
        ),
    ]
